<?php

/*
 * This file is a part of PHPAX-RS framework, released under terms of GPL-3.0
 * licence. Copyright (c) 2014, UnArt Slavičín, o.s. All rights reserved.
 */

namespace phpaxrs\common;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-05 at 16:40:21.
 */
class DocCommentWrapperTest extends \PHPUnit_Framework_TestCase {

    public function parseProvider() {
        return array(
            array(
                "/** @GET\n"
                . " *\n"
                . " *\n"
                . " * @Path(/abs/{id:[0-9]+})\n"
                . " * @Consumes(application/json)\n"
                . " * @Consumes(text/plain)\n"
                . " */",
                array(
                    'GET' => array(),
                    'Path' => array('/abs/{id:[0-9]+}'),
                    'Consumes' => array('application/json', 'text/plain')
                )
            )
        );
    }
    
    /**
     * @covers phpaxrs\common\DocCommentWrapper::parse
     * @dataProvider parseProvider
     */
    public function testParse($doc_comment, $expected) {
        $this->assertEquals($expected, DocCommentWrapper::parse($doc_comment));
    }

}
