<?php

/*
 * This file is a part of PHPAX-RS framework, released under terms of GPL-3.0
 * licence. Copyright (c) 2014, UnArt, o.s. All rights reserved.
 */

namespace phpaxrs\common;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-05 at 16:04:08.
 */
class HttpUtilTest extends \PHPUnit_Framework_TestCase {

    public function headers() {
        return array(
            array(
                '*/*;q=0.5, text/javascript, application/javascript',
                array(
                    'text/javascript', 'application/javascript', '*/*'
                )
            ),
            array(
                'text/html, */*; q=0.01',
                array(
                    'text/html', '*/*'
                )
            )
        );
    }

    /**
     * @covers phpaxrs\common\HttpUtil::parse_accept_header
     * @dataProvider headers
     */
    public function testParse_accept_header($header, $expected) {
        $this->assertEquals($expected, HttpUtil::parse_accept_header($header));
    }

}
